### DEP PAR Relations #########
pred="PREDICATE"
mod="MODIFIER"
deriv ="DERIV"
det="DETERMINER"
poss="POSSESSOR"
conj="CONJUNCTION"
coord="COORDINATION"
cau="AM-CAU"
goal="AM-GOL"
ext="AM-EXT"
am_neg ="AM-NEG"
subj="SUBJECT"
compound="MWE:NCOMP"
numex ="MWE:NUMEX"
enamex="MWE:ENAMEX"
dub="MWE:DUP"
two="AM-TWO"
mwe_conj="MWE:CONJ"
obj="OBJECT"
arg="ARGUMENT"
appos="APPOSITION"
pers="PERS"
org="ORG"
loc="LOC"
pct="PCT"


##### POS TAG #####
verb="Verb"
punc="Punc"
domain="domain"
pron="Pron"
adj="Adj"
adv="Adverb"
noun="Noun"
nadj="NAdj"
aor="AorPart"
conj_as_if="conj-as-if"
ques="Ques"
cnjc="Conj"
num="Num"


#### Propbank Relations #####
AA="A-A"
A0="A0"
A1="A1"
A2="A2"
A3="A3"
A4="A4"
A5="A5"

### Reification #######
A0_of="A0-of"
cause_of="cause-of"
A1_of="A1-of"
sahip_ilişki_role_91="sahip-ilişki-role-91"



##### Concept#######
ol14="ol.14"
concept_bu = "bu"
concept_su="şu"
possible = "mümkün.01"
eksi="-"
yap="yap"
ve="and"
ol17="ol.17"
ol01="ol.01"
ki="ki"
person="person"
thing="thing"
gibi="gibi"
benze="benze.01"
boyle="böyle"
soyle="şöyle"
or_="karşılaştır.01"
unit="unit"
amr_unknown="amr-unknown"
ne="ne"
neden="neden"
nereden="nereden"
nasil="nasıl"
kadar="kadar"
ayni="aynı"
en="en"
icin="için"
ile="ile"
suffix_de="de"
suffix_ya="ya"
suffix_da="da"
ara="ara"
ama = "ama"
fakat= "fakat"
veya="veya"
hem="hem"
eger="eğer"
single="single"
name="name"
wiki="wiki"
isim="name"
ulke="ülke"
onay_talebi="onay-talebi"
gun="gün"
ay="ay"
suan="şuan"
kere="kere"
cok="çok"
zaman="zaman"
o="o"
yuz="yüz"
yap_="yap.03"




##### Inflectional Properties ########
able="Able"
neg="Neg"
imp="Imp"
necessity="Neces"
condition="Cond"
condition_="condition"
caus="Caus"


###### Alignment Keys########
remove_token_child_up="remove-token-pre-token-up"
child_up_parent_down="up-token-parent-down"
only_parent_rel="only-parent-rel"
function_based="function-based"
special_cases="special_cases"
quantity="quantity"
approximation="approximation"
negation="negation"
question="question"
wh_questions="wh-questions"
have_degre="have-degree"
have_relation="have-relation"
time_temporal_words="time-temporal-words"
det_to_mod="det-to-mod"
non_relations="non-relations"
locations="locations"
name_entities="name-entities"
date_entity="date-entity"
nationality="nationality"
percentage="percentage"
percentage_entity="percentage-entity"


####### AMR #######
imperative = "imperative"
polarity="polarity"
medium="medium"
example="example"
quant="quant"
frequency="frequency"
manner="manner"
topic="topic"
op="op"
op1="op1"
op2="op2"
mod_rel="mod"
degree="degree"
time="time"
beneficiary="beneficiary"
purpose="purpose"
instrument="instrument"
organizasyon="organizasyon"
value="value"
add_topic="add_topic"
add_benze_frame="add_benze_frame"
handle_modality_words="handle_modality_words"
change_olarak="change_olarak"


ip="AfterDoingSo"
arak="ByDoingSo"
madan="WithoutHavingDoneSo"
ince="When"
ken="While"
prep_after="prep-after"
prep_by="prep-by"
prep_without="prep-without"
prep_when="time"
prep_while="prep-while"
